swagger: 2.0
info:
  version: "0.0.1"
  title: FiledownloadToken API
basePath: /filedownload
paths:
  /token:
    get:
      description:
      parameters:
        - name: pageSize
          in: query
          type: number
          description: size of list
          required: false
        - name: page
          in: query
          type: integer
          description: page
          required: false
        - name: sortingDirection
          in: query
          type: string
          description: DESC | ASC
          required: false
        - name: sortingFields
          in: query
          type: string
          description: sorting fields
          required: false
      responses:
        200:
          description: Successful response
          schema:
            title: ArrayOfFiledownloadToken
            type: array
            items:
              $ref: '#/definitions/FiledownloadToken'
    get:
      parameters:
        - name: FiledownloadToken
          in: body
          description: The FiledownloadToken JSON you want to post
          schema:
            $ref: '#/definitions/FiledownloadToken'
    post:
      parameters:
        - name: FiledownloadToken
          in: body
          description: The FiledownloadToken JSON you want to post
          schema:
            $ref: '#/definitions/FiledownloadToken'
    put:
      parameters:
        - name: FiledownloadToken
          in: body
          description: The FiledownloadToken JSON you want to post
          schema:
            $ref: '#/definitions/FiledownloadToken'
    delete:
      parameters:
        - name: FiledownloadToken
          in: body
          description: The FiledownloadToken JSON you want to post
          schema:
            $ref: '#/definitions/FiledownloadToken'
definitions:
  FiledownloadToken:
    type: object
    properties:
