swagger: 2.0
info:
  version: "0.0.1"
  title: PickingJob API
basePath: /picking
paths:
  /job:
    get:
      description:
      parameters:
        - name: pageSize
          in: query
          type: number
          description: size of list
          required: false
        - name: page
          in: query
          type: integer
          description: page
          required: false
        - name: sortingDirection
          in: query
          type: string
          description: DESC | ASC
          required: false
        - name: sortingFields
          in: query
          type: string
          description: sorting fields
          required: false
      responses:
        200:
          description: Successful response
          schema:
            title: ArrayOfPickingJob
            type: array
            items:
              $ref: '#/definitions/PickingJob'
    get:
      parameters:
        - name: PickingJob
          in: body
          description: The PickingJob JSON you want to post
          schema:
            $ref: '#/definitions/PickingJob'
    post:
      parameters:
        - name: PickingJob
          in: body
          description: The PickingJob JSON you want to post
          schema:
            $ref: '#/definitions/PickingJob'
    put:
      parameters:
        - name: PickingJob
          in: body
          description: The PickingJob JSON you want to post
          schema:
            $ref: '#/definitions/PickingJob'
    delete:
      parameters:
        - name: PickingJob
          in: body
          description: The PickingJob JSON you want to post
          schema:
            $ref: '#/definitions/PickingJob'
definitions:
  PickingJob:
    type: object
    properties:
