swagger: 2.0
info:
  version: "0.0.1"
  title: Printer API
basePath: /
paths:
  /printer:
    get:
      description:
      parameters:
        - name: pageSize
          in: query
          type: number
          description: size of list
          required: false
        - name: page
          in: query
          type: integer
          description: page
          required: false
        - name: sortingDirection
          in: query
          type: string
          description: DESC | ASC
          required: false
        - name: sortingFields
          in: query
          type: string
          description: sorting fields
          required: false
      responses:
        200:
          description: Successful response
          schema:
            title: ArrayOfPrinter
            type: array
            items:
              $ref: '#/definitions/Printer'
    get:
      parameters:
        - name: Printer
          in: body
          description: The Printer JSON you want to post
          schema:
            $ref: '#/definitions/Printer'
    post:
      parameters:
        - name: Printer
          in: body
          description: The Printer JSON you want to post
          schema:
            $ref: '#/definitions/Printer'
    put:
      parameters:
        - name: Printer
          in: body
          description: The Printer JSON you want to post
          schema:
            $ref: '#/definitions/Printer'
    delete:
      parameters:
        - name: Printer
          in: body
          description: The Printer JSON you want to post
          schema:
            $ref: '#/definitions/Printer'
definitions:
  Printer:
    type: object
    properties:
