swagger: 2.0
info:
  version: "0.0.1"
  title: WarehouseAisle API
basePath: /warehouse
paths:
  /aisle:
    get:
      description:
      parameters:
        - name: pageSize
          in: query
          type: number
          description: size of list
          required: false
        - name: page
          in: query
          type: integer
          description: page
          required: false
        - name: sortingDirection
          in: query
          type: string
          description: DESC | ASC
          required: false
        - name: sortingFields
          in: query
          type: string
          description: sorting fields
          required: false
      responses:
        200:
          description: Successful response
          schema:
            title: ArrayOfWarehouseAisle
            type: array
            items:
              $ref: '#/definitions/WarehouseAisle'
    get:
      parameters:
        - name: WarehouseAisle
          in: body
          description: The WarehouseAisle JSON you want to post
          schema:
            $ref: '#/definitions/WarehouseAisle'
    post:
      parameters:
        - name: WarehouseAisle
          in: body
          description: The WarehouseAisle JSON you want to post
          schema:
            $ref: '#/definitions/WarehouseAisle'
    put:
      parameters:
        - name: WarehouseAisle
          in: body
          description: The WarehouseAisle JSON you want to post
          schema:
            $ref: '#/definitions/WarehouseAisle'
    delete:
      parameters:
        - name: WarehouseAisle
          in: body
          description: The WarehouseAisle JSON you want to post
          schema:
            $ref: '#/definitions/WarehouseAisle'
definitions:
  WarehouseAisle:
    type: object
    properties:
