swagger: 2.0
info:
  version: "0.0.1"
  title: WarehouseLevel API
basePath: /warehouse
paths:
  /level:
    get:
      description:
      parameters:
        - name: pageSize
          in: query
          type: number
          description: size of list
          required: false
        - name: page
          in: query
          type: integer
          description: page
          required: false
        - name: sortingDirection
          in: query
          type: string
          description: DESC | ASC
          required: false
        - name: sortingFields
          in: query
          type: string
          description: sorting fields
          required: false
      responses:
        200:
          description: Successful response
          schema:
            title: ArrayOfWarehouseLevel
            type: array
            items:
              $ref: '#/definitions/WarehouseLevel'
    get:
      parameters:
        - name: WarehouseLevel
          in: body
          description: The WarehouseLevel JSON you want to post
          schema:
            $ref: '#/definitions/WarehouseLevel'
    post:
      parameters:
        - name: WarehouseLevel
          in: body
          description: The WarehouseLevel JSON you want to post
          schema:
            $ref: '#/definitions/WarehouseLevel'
    put:
      parameters:
        - name: WarehouseLevel
          in: body
          description: The WarehouseLevel JSON you want to post
          schema:
            $ref: '#/definitions/WarehouseLevel'
    delete:
      parameters:
        - name: WarehouseLevel
          in: body
          description: The WarehouseLevel JSON you want to post
          schema:
            $ref: '#/definitions/WarehouseLevel'
definitions:
  WarehouseLevel:
    type: object
    properties:
