swagger: 2.0
info:
  version: "0.0.1"
  title: WarehouseEmployee API
basePath: /warehouse
paths:
  /employee:
    get:
      description:
      parameters:
        - name: pageSize
          in: query
          type: number
          description: size of list
          required: false
        - name: page
          in: query
          type: integer
          description: page
          required: false
        - name: sortingDirection
          in: query
          type: string
          description: DESC | ASC
          required: false
        - name: sortingFields
          in: query
          type: string
          description: sorting fields
          required: false
      responses:
        200:
          description: Successful response
          schema:
            title: ArrayOfWarehouseEmployee
            type: array
            items:
              $ref: '#/definitions/WarehouseEmployee'
    get:
      parameters:
        - name: WarehouseEmployee
          in: body
          description: The WarehouseEmployee JSON you want to post
          schema:
            $ref: '#/definitions/WarehouseEmployee'
    post:
      parameters:
        - name: WarehouseEmployee
          in: body
          description: The WarehouseEmployee JSON you want to post
          schema:
            $ref: '#/definitions/WarehouseEmployee'
    put:
      parameters:
        - name: WarehouseEmployee
          in: body
          description: The WarehouseEmployee JSON you want to post
          schema:
            $ref: '#/definitions/WarehouseEmployee'
    delete:
      parameters:
        - name: WarehouseEmployee
          in: body
          description: The WarehouseEmployee JSON you want to post
          schema:
            $ref: '#/definitions/WarehouseEmployee'
definitions:
  WarehouseEmployee:
    type: object
    properties:
