swagger: 2.0
info:
  version: "0.0.1"
  title: Menu API
basePath: /
paths:
  /menu:
    get:
      description:
      parameters:
        - name: pageSize
          in: query
          type: number
          description: size of list
          required: false
        - name: page
          in: query
          type: integer
          description: page
          required: false
        - name: sortingDirection
          in: query
          type: string
          description: DESC | ASC
          required: false
        - name: sortingFields
          in: query
          type: string
          description: sorting fields
          required: false
      responses:
        200:
          description: Successful response
          schema:
            title: ArrayOfMenu
            type: array
            items:
              $ref: '#/definitions/Menu'
    get:
      parameters:
        - name: Menu
          in: body
          description: The Menu JSON you want to post
          schema:
            $ref: '#/definitions/Menu'
    post:
      parameters:
        - name: Menu
          in: body
          description: The Menu JSON you want to post
          schema:
            $ref: '#/definitions/Menu'
    put:
      parameters:
        - name: Menu
          in: body
          description: The Menu JSON you want to post
          schema:
            $ref: '#/definitions/Menu'
    delete:
      parameters:
        - name: Menu
          in: body
          description: The Menu JSON you want to post
          schema:
            $ref: '#/definitions/Menu'
definitions:
  Menu:
    type: object
    properties:
