swagger: 2.0
info:
  version: "0.0.1"
  title: PickingItemInfo API
basePath: /picking
paths:
  /item:
    get:
      description:
      parameters:
        - name: pageSize
          in: query
          type: number
          description: size of list
          required: false
        - name: page
          in: query
          type: integer
          description: page
          required: false
        - name: sortingDirection
          in: query
          type: string
          description: DESC | ASC
          required: false
        - name: sortingFields
          in: query
          type: string
          description: sorting fields
          required: false
      responses:
        200:
          description: Successful response
          schema:
            title: ArrayOfPickingItemInfo
            type: array
            items:
              $ref: '#/definitions/PickingItemInfo'
    get:
      parameters:
        - name: PickingItemInfo
          in: body
          description: The PickingItemInfo JSON you want to post
          schema:
            $ref: '#/definitions/PickingItemInfo'
    post:
      parameters:
        - name: PickingItemInfo
          in: body
          description: The PickingItemInfo JSON you want to post
          schema:
            $ref: '#/definitions/PickingItemInfo'
    put:
      parameters:
        - name: PickingItemInfo
          in: body
          description: The PickingItemInfo JSON you want to post
          schema:
            $ref: '#/definitions/PickingItemInfo'
    delete:
      parameters:
        - name: PickingItemInfo
          in: body
          description: The PickingItemInfo JSON you want to post
          schema:
            $ref: '#/definitions/PickingItemInfo'
definitions:
  PickingItemInfo:
    type: object
    properties:
