swagger: 2.0
info:
  version: "0.0.1"
  title: PrinterLabel API
basePath: /printer
paths:
  /label:
    get:
      description:
      parameters:
        - name: pageSize
          in: query
          type: number
          description: size of list
          required: false
        - name: page
          in: query
          type: integer
          description: page
          required: false
        - name: sortingDirection
          in: query
          type: string
          description: DESC | ASC
          required: false
        - name: sortingFields
          in: query
          type: string
          description: sorting fields
          required: false
      responses:
        200:
          description: Successful response
          schema:
            title: ArrayOfPrinterLabel
            type: array
            items:
              $ref: '#/definitions/PrinterLabel'
    get:
      parameters:
        - name: PrinterLabel
          in: body
          description: The PrinterLabel JSON you want to post
          schema:
            $ref: '#/definitions/PrinterLabel'
    post:
      parameters:
        - name: PrinterLabel
          in: body
          description: The PrinterLabel JSON you want to post
          schema:
            $ref: '#/definitions/PrinterLabel'
    put:
      parameters:
        - name: PrinterLabel
          in: body
          description: The PrinterLabel JSON you want to post
          schema:
            $ref: '#/definitions/PrinterLabel'
    delete:
      parameters:
        - name: PrinterLabel
          in: body
          description: The PrinterLabel JSON you want to post
          schema:
            $ref: '#/definitions/PrinterLabel'
definitions:
  PrinterLabel:
    type: object
    properties:
